//tag::ref-doc[]
= CoAP Observe Source

Subscribes to CoAP `observable` resources. Listens for CoAP resource updates and emits the body as a message payload.
The message Content-Type is extracted from the request format type if available or defaults to `text/*` otherwise.
The payload is byte array.

== Input

N/A

== Output

==== Headers:

* `Content-Type` - Request/s format type

==== Payload:

A `byte[]` filled with the request payload.

== Options

The **$$file$$** $$source$$ has the following options:

//tag::configuration-properties[]
$$coap.dtls.enabled$$:: $$Enable or disable the DTLS transport encryption$$ *($$Boolean$$, default: `$$false$$`)*
$$coap.dtls.identity$$:: $$PSK identity if required to authenticate with teh CoAP Server$$ *($$String$$, default: `$$<none>$$`)*
$$coap.dtls.key-store-alias$$:: $$Keystore user alias$$ *($$String$$, default: `$$client$$`)*
$$coap.dtls.key-store-location$$:: $$DTLS key store location. (supports file:// , classpath:/ or http:/)$$ *($$String$$, default: `$$classpath:/clientKeyStore.jks$$`)*
$$coap.dtls.key-store-password$$:: $$Keystore password$$ *($$String$$, default: `$$clientPass$$`)*
$$coap.dtls.secret$$:: $$PSK password if required to authenticate with teh CoAP Server$$ *($$String$$, default: `$$<none>$$`)*
$$coap.dtls.trust-store-location$$:: $$DTLS Trust store location (supports file:// , classpath:/ or http:/)$$ *($$String$$, default: `$$classpath:/cacerts$$`)*
$$coap.dtls.trust-store-password$$:: $$Trust store password$$ *($$String$$, default: `$$changeit$$`)*
$$coap.observe.url$$:: $$CoAP Resource uri to observer$$ *($$String$$, default: `$$<none>$$`)*
//end::configuration-properties[]

The `ref` option is useful in some cases in which the file contents are large and it would be more efficient to send the file path.

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps

You can find the corresponding binder based projects here. You can then cd into one of the folders and build it:

$ ./mvnw clean package
```

== Examples

```
java -jar coap-observe-source.jar --coap.observe.url=coap://californium.eclipse.org:5683/obs
```

with `DTSL`
```
java -jar coap-observe-source.jar --coap.observe.url=coaps://californium.eclipse.org:5684/obs --coap.dtls.enabled=true \
    --coap.dtls.keyStoreLocation=file:/<full path>/clientKeyStore.jks \
    --coap.dtls.trustStoreLocation=file:/<full path>/cacerts
```

//end::ref-doc[]
